# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 신복호
title: DevOps Engineer
email: gjrjr4545@gmail.com
website: velog.io/@gjrjr4545/posts

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  bocopile
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  인프라 아키텍처 설계 및 시스템 자동화를 좋아하는 8년차 개발자 신복호 입니다.
  
  퍼블릭 클라우드 및 온프레미스 환경에서 CI/CD 파이프라인, 모니터링 시스템, 트래픽 기반 아키텍처 자동화를 구축해왔습니다. 
  Kubernetes, Jenkins, Prometheus, HAProxy 등을 활용해 대형 고객사의 인프라 운영 자동화를 수행하며, 안정성과 비용 최적화를 중점적으로 고려하였습니다.
  
  또한, CI/CD 개선, 장애 대응 프로세스 구축, 통합 모니터링 도입 등 DevOps 문화 확산과 개발 효율성 향상에 기여해왔습니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 어니컴 주식회사
        link: https://imqa.io
        sub_title: DevOps 엔지니어
        caption: 2022.02 ~ 2024.10
        link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote:
        description: | # this will include new lines to allow paragraphs
         <mark> IMQA 모바일 모니터링 솔루션 서비스 </mark>
          
          [아키텍처 설계 및 인프라 구축]
           - 대형 고객사(은행, 보험) 대상 최대 일일 100만 트래픽 처리 아키텍처 설계 및 구축
           - GSIP 국가 과제 목적 아키텍처 설계 및 인프라 구축
           - CSAP 검증용 네이터 블라우드 기반 k8s 아키텍처 설계 및 인프라 구축
         
          [최적화/자동화]
           - Azure 기반 서비스 데이터 필터링 및 고객사별 Region 분리하여 인프라 구축(기존 대비 60% 인프라 비용 절감)
           - Node 기반 프로젝트 경량화 및 Jenkins CI/CD 구축(기존 대비 배포 소요시간 50% 단축)
           - Shell 기반 IMQA 자동 복구 시스템 구축
           - Node 기반 DB 배포/검증 자동화 시스템 구축
           - IMQA 서비스 일괄 설치/배포 자동화 시스템 구축
          
          [모니터링 시스템 구축]
           - 퍼블릭 클라우드 통합 <a href = "https://velog.io/@gjrjr4545/monitoring-0" >모니터링 시스템</a>(Node Exporter, Prometheus, Loki, Grafana) 구축
           
          [운영 정책 수립]
           - 퍼블릭 클라우드 및 온프레미스 시스템 별 장애 대응 방안 및 표준 운영 프로세스 수립
           
         <mark> AI 융합 불법복제품 판독 솔루션 서비스 </mark>
          - Node 기반 물품 불법복제품 판독 솔루션 아키텍처 및 인프라 구축
          - 물품 불법복제판독 비교 비지니스 API 작업 진행
          
         <mark> AI 안면인식 판독 솔루션 서비스 </mark>
          - Node 기반 안면인식 판독 솔루션 아키텍처 및 인프라 구축
          - RTMP 영상 라이브 스트리밍, 영상/사진 비교 비지니스 API 작업 진행

      - layout: left
        title: 주식회사 에스엔비플러스
        sub_title: 백엔드 개발자
        caption: 2018.10 ~ 2021.02
          # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote:
        description: | # this will include new lines to allow paragraphs
          <mark> 동반성장몰 소상공인 소셜커머스 시스템 리뉴얼 </mark>
           - 쿠폰, 핫딜 상품, 공동구매, 라이브커머스 연동 비지니스 API 개발
           - 외부 NetFUNNEL 적용 작업    
           - Jmeter, Scouter 기반 부하 테스트 진행
          
          <mark> 국립국어원 한국어교원 자격심사 시스템 </mark>
          - 메인 담당자로서 시스템 유지보수 및 고객응대
          - 전자정부기반 CMS 보안 강화
          - Electron 기반 개인정보 문서스캔 시스템 솔루션 개발
          
          <mark> 국립국어원 지역어 시스템 </mark>
          - 유지보수 담당자, 관리자 및 사용자에 대한 유지보수 작업 진행
          - 네이버 지도 엔진 기반 지역어 맵서비스 구축
          - Node, Selenium 기반으로 지도 이미지 변환 자동화 구축
          
          <mark> 검정고시 자격심사 고도화 사업 </mark>
          - 메인 담당자로서 유지보수 업무 및 고객 응대
          - 검정고시 내부 LMS 기능 구축
          - MSA 기반으로 된 보안작업을 통한 PMS 연동 작업
          
          <mark> 사내 내부 인트라넷 구축
          - Spring Boot/Vue 기반 사내 내부 인트라넷 구축
          - 회원/결제문서/사내커뮤니케이션/사업관리와 같은 비즈니스 컴포넌트 설계 및 개발
          - Docker를 이용하여 배포 자동화 구축
          - MSA 기반 Spring Cloud 적용
          
          <mark> KAIT 시스템 유지보수 작업 </mark>
          - 한국정보통신진흥협회 정보통신기술자격검증 시스템 개발 및 유지보수 작업
          - C++ 기반 답안전송시스템(MFC) 유지보수 작업
          - Spring 기반 시험접수 시스템 구축 작업
          
          <mark> 기타 </mark>
          - Jira를 이용한 스크럼 진행
          - Confluence를 이용한 위키 문화
          - Bitburket을 이용한 버전관리 적용
          - 매달 내부 기술 세미나 개최 (Docker, HeadlessBrowser, Scrum 등 업무와 관련된 컨퍼런스 진행)

      - layout: left
        title: (주)더인
        sub_title: 백엔드 개발자
        caption: 2016.12 ~ 2018.06
          # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote:
        description: | # this will include new lines to allow paragraphs
          <mark> 코원 에너지 서비스 리뉴얼 </mark>
           - Spring 기반 예약, 기사매칭, 요금부과 관련 비지니스 컴포넌트 개발
           - Jmeter 기반 부하 테스트 작업
          
          <mark> nailook - 네일아트 매칭 플랫폼 </mark>
          - Spring 기반 네일아트 매칭 플랫폼 개발
          - 네일아트 갤러리 및 예약 관련 기능 비지니스 API 작업
          
          <mark> Dr.physio - 의료 정보 솔루션  </mark>
          - 2017.02 ~ 2017.08
          - Spring, Mysql 의료 정보 솔루션 개발
          - 고객 물리치료, 환자 관리 비지니스 API 작업 진행
          - 내부 관리자 전용 CMS API 작업 진행

  - title: 역량 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 내부 개발 파티 및 개발 조직 문화 개선 참가
        caption:
        sub_title:
        description: | # this will include new lines to allow paragraphs
          - (어니컴) 2023 IMDev 컨퍼런스 발표 - <a href="https://www.youtube.com/watch?v=MdrOjh_aIxw"> IMQA Container 환경 서비스 제공 적용기 </a>
          - (어니컴) IMQA Blog 포스팅 진행
          - (SnB플러스) Jira를 이용한 스크럼 진행
          - (SnB플러스) Confluence를 이용한 위키 문화
          - (SnB플러스) Bitburket을 이용한 버전관리 적용
          - (SnB플러스) 매달 내부 기술 세미나 참가 (Docker, HeadlessBrowser, Scrum 등 업무와 관련된 컨퍼런스 진행)

      - layout: left
        title: Devops
        caption:
        sub_title:
        description: | # this will include new lines to allow paragraphs
          - (어니컴) 고객사별 트래픽 대비 아키텍처 설계 및 시스템 구축
          - (어니컴) Node 기반 프로젝트 경량화 및 Jenkins 기반 CI/CD 파이프라인 구축
          - (어니컴) 통합 모니터링 시스템 구축 (Node Exportor, Prometheus, Loki, Grafana 등)
          - (어니컴) DB 배포 및 검증 자동화 시스템 구축

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        sub_title: (Java 프로젝트 80%, Node 프로젝트 20%)
        description: | # this will include new lines to allow paragraphs
          - Java, Spring Boot, Spring MVC, Spring Security, Spring Data JPA
          - Nodejs, Express, TypeORM, Jest

      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Jenkins, Github Action
          - Nginx, HaProxy, RabbitMQ, Redis
          - AKS, Linux
          - Prometheus, Grafana, Loki 

  - title: 대외활동 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ImDev 컨퍼런스
        description: | # this will include new lines to allow paragraphs
          - 2023 ImDev 컨퍼런스 참가
          - <a href="https://conference.imqa.io/"> 2023 IMDev 스피커 - IMQA Container 환경 서비스 제공 적응기 </a>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한국방송통신대학교
        caption: 2017.03 - 2019.02
        sub_title: 컴퓨터과학과 (졸업)
        description: | # this will include new lines to allow paragraphs
          - JAVA, 자료구조,알고리즘 운영 체제, 네트워크, 인공지능 교육
          - 졸업 논문 : 전자정부프레임워크에 대한 고찰

      - layout: left
        title: 경기과학기술대학교
        caption: 2017.03 - 2019.02
        sub_title: 신재생에너지학과



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
