# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 신복호
title: DevOps Engineer
email: gjrjr4545@gmail.com
website: velog.io/@gjrjr4545/posts

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  bocopile
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Azure 및 온프레미스 환경에서 안정적인 서비스 제공과 효율적인 운영을 위한 CI/CD 파이프라인,
  온프레미스 설치 간편화, 모니터링 시스템 구축, 트래릭 기반 아키텍처 설계 및 자동화 솔루션 경험이 있는 8년차 엔지니어 입니다.


content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java, NodeJS
          - Spring Boot, Spring MVC, Spring Security, Spring Data JPA
          - Jest, Junit5
          - Gradle, Maven
          - IntelliJ, WebStorm, Visual Studio Code
          

      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - MySQL, MariaDB
          - Jenkins, Github Action
          - Terraform, ansible
          - Nginx, HaProxy, RabbitMQ
          - Linux Centos



  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 어니컴 주식회사
        link: imqa.io
        sub_title: DevOps 엔지니어
        caption: 2022.02 ~
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         <mark>JAVA</mark> <mark>Node</mark> <mark>shell</mark> <mark>Go</mark> <mark>Docker</mark> <mark> CI/CD </mark> <mark>Github Action</mark> <mark>Terraform</mark> <mark>Mysql</mark>
        description: | # this will include new lines to allow paragraphs
         <mark> IMQA 모바일 모니터링 솔루션 DevOps 파트 담당자 </mark>
          - 2022.02 ~ 현재
          
         [saas]
          - Node 18 NCC 배포 Jenkins 기반 CI/CD 파이프라인 구축
          - Grafana 및 Opensearch 기반 통합 모니터링 시스템 구축
          - Azure SaaS 운영 담당
          
         [On-Premise]
          - 은행, 보험, 증권사등 대형 고객사 트래픽 기반 서버 아키텍처 설계
          - Shell 기반 On-Premise 일괄 설치 스크립트 구축
          - On-Premise 고객사 서버 구축 작업
          - Shooting 가이드 및 대응 프로세스 구축
          - 고객사 정기 및 핫픽스 배포 담당
          - 시스템 Health Check 기능 구축
          
          [공통]
          - SQL 배포 및 검증 자동화 기능 개발
          - Jmeter 기반 부하 테스트 진행
          - 인프라 트러블 슈팅 진행 (Redis, Mysql, RabbitMQ, pm2, Haproxy 등)
          - SaaS 및 On-Premise 트래픽 기반 시스템 아키텍처 및 운영 정책 수립
          - Cockatiel 기반 Circuit Breaker 구축
          
          <mark> AI 융합 불법복제품 판독 시스템 메인 담당자 </mark>
          - 기간 : 2021.07 ~ 2022.12
          - Node 12 기반 물품 비교 검증 솔루션 구축
          - 관세청 물품 비교 검증 메인 담당
          
          <mark> AI 안면인식 과제 메인 담당자 </mark>
          - 기간 : 2021.03 ~ 2022.12
          - Node 12 기반 안면인식 비교 검증 솔루션 구축
          - RTMP 기반 안면인식 영상 라이브 스트리밍 시스템 구축
          - 안면인식 검증 메인 담당

      - layout: left
        title: 주식회사 에스엔비플러스
        sub_title: 백엔드 개발자
        caption: 2018.10 ~ 2021.02
          # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          <mark>JAVA</mark> <mark>spring</mark> <mark>python</mark> <mark>Mysql</mark>
        description: | # this will include new lines to allow paragraphs
          <mark> 가치삽시다/동반성장몰 소상공인 소셜 커머스 사업 리뉴얼 </mark>
           - 2020.09 ~ 2021.02
           - 핫딜 상품, 베스트, 공동구매 API 개발
           - 외부 NetFUNNEL 적용 작업    
           - jmeter, scouter 기반 부하 테스트 진행
          
          <mark> 국립국어원 한국어교원 자격심사 시스템 </mark>
          - 2019.04 ~ 2020.09
          - 유지보수 업무 및 고객응대
          - 전자정부기반 CMS 보안 강화
          - Electron 기반 개인정보 문서스캔 시스템 솔루션 개발
          
          <mark> 검정고시 자격심사 고도화 사업 </mark>
          - 2019.10 ~ 2020.03
          - 자격심사 사이트 메인 API 개발자
          - LMS 기능 구축
          - MSA 기반으로 된 보안작업을 통한  PMS 연동 작업
          
          <mark> 사내 내부 인트라넷 구축
          - 2019.08 ~ 2020.06
          - Spring Boot 기반 사내 내부 인트라넷 구축
          - 비지니스 컴포넌트 설계 및 개발 진행
          - MSA 기반 spring cloud 구축 진행
          
          <mark> 국립국어원 지역어 관련 리뉴얼 </mark>
          - 유지보수 담당자, 관리자 및 사용자에 대한 유지보수 작업 진행
          - 네이버 지도 엔진 기반 지역어 맵서비스 구축
          - Node, Selenium 기반으로 지도 이미지 변환 자동화 구축
          
          <mark> KAIT 시스템 유지보수 작업 </mark>
          - 한국정보통신진흥협회 정보통신기술자격검증 시스템 개발 및 유지보수 작업
          - C++ 기반 답안전송시스템(MFC) 유지보수 작업
          - Spring 기반 시험접수 시스템 구축 작업

      - layout: left
        title: (주)더인
        sub_title: 백엔드 개발자
        caption: 2016.12 ~ 2018.06
          # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          <mark>JAVA</mark> <mark>spring</mark> <mark>python</mark> <mark>Mysql</mark>
        description: | # this will include new lines to allow paragraphs
          <mark> 코원 에너지 서비스(SK E&S) 시스템 리뉴얼 </mark>
           - 2018.02 - 2018.05
           - Spring 기반 예약, 기사매칭, 요금부과 관련 비지니스 컴포넌트 개발
           - 리뉴얼 관련 전체적 부하 테스트 작업
          
          <mark> nailook - 네일아트 플랫폼 </mark>
          - 2017.09 ~ 2018.02
          - Spirng, ionic 기반 네일아트 시스템 백엔드 개발
          - 네일아트 갤러리 및 예약 관련 기능 비지니스 API 작업
          
          <mark> Dr.physio - 의료 정보 솔루션  </mark>
          - 2017.02 ~ 2017.08
          - Spring, Mysql 의료 정보 솔루션 구축
          - 고객 물리치료 관리 솔루션 구축 작업
          - 내부 관리자를 위한 CMS 구축 작업
        
         

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한국방송통신대학교
        caption: 2017.03 - 2019.02
        sub_title: 컴퓨터과학과 (졸업)
        quote: >
          컴퓨터 공학 교육
        description: | # this will include new lines to allow paragraphs
          - JAVA, 자료구조,알고리즘 운영 체제, 네트워크, 인공지능 교육
          - 졸업 논문 : 전자정부프레임워크에 대한 고찰

      - layout: left
        title: 경기과학기술대학교
        caption: 2017.03 - 2019.02
        sub_title: 신재생에너지학과



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
